Repository riidefi/mkw, pull requests merged in 2021-07, with the labels that each got.

#21 Decompile RVL/MEM
  asm/dol/bss_802a4080_80346cf0.s
  asm/dol/bss_802a4080_803832d8.s
  asm/dol/bss_80346d18_803832d8.s
  asm/dol/sbss_803862b0_80386838.s
  asm/dol/sbss_803862b0_80386d80.s
  asm/dol/sbss_8038683c_80386d80.s
  asm/dol/sdata2_80387eb4_80388860.s
  asm/dol/sdata2_80387eb4_80388870.s
  build.py
  mkwutil/gen_asm.py
  mkwutil/verify_object_file.py
  pack/dol.base.lcf
  pack/dol_objects.txt
  pack/dol_slices.csv
  source/egg/core/eggArchive.cpp
  source/egg/core/eggArchive.hpp
  source/egg/core/eggHeap.cpp
  source/egg/core/eggHeap.hpp
  source/egg/core/eggUnitHeap.cpp
  source/platform/math.h
  source/platform/stdlib.h
  source/platform/string.h
  source/rvl/mem/expHeap.h
  source/rvl/mem/frmHeap.h
  source/rvl/mem/heap.h
  source/rvl/mem/heapi.h
  source/rvl/mem/memAllocator.h
  source/rvl/mem/rvlMemAllocator.c
  source/rvl/mem/rvlMemExpHeap.c
  source/rvl/mem/rvlMemFrmHeap.c
  source/rvl/mem/rvlMemHeap.c
  source/rvl/mem/rvlMemList.c
  source/rvl/mem/rvlMemList.h
  source/rvl/mem/rvlMemUnitHeap.c
  source/rvl/mem/unitHeap.h
  source/rvl/mtx/rvlMtx.c
  source/rvl/os/osThread.h
  sources.py
Labels: decomp, p-high, rvl

#23 Copy nw4r code from doldecomp/ogws
  asm/dol/bss_802a4080_802bd4ec.s
  asm/dol/bss_802a4080_80346cf0.s
  asm/dol/bss_802bd4ec_80346cf0.s
  asm/dol/sdata2_80386fa0_80387cac.s
  asm/dol/sdata2_80386fa0_80387e80.s
  asm/dol/sdata2_80387cd8_80387d58.s
  asm/dol/sdata2_80387d5c_80387e80.s
  asm/dol/text_8006a518_800774d0.s
  asm/dol/text_800775d0_80085110.s
  pack/dol.base.lcf
  pack/dol_objects.txt
  pack/dol_slices.csv
  source/nw4r/g3d/g3d_camera.cpp
  source/nw4r/g3d/g3d_camera.hpp
  source/nw4r/g3d/g3d_fog.cpp
  source/nw4r/g3d/g3d_fog.hpp
  source/nw4r/g3d/g3d_rescommon.h
  source/nw4r/g3d/g3d_state.hpp
  source/nw4r/math/mathTypes.h
  source/nw4r/ut/utColor.hpp
  source/nw4r/ut/utList.hpp
  source/rvl/gx/gx.h
  source/rvl/gx/gxFrameBuf.h
  source/rvl/gx/gxPixel.h
  source/rvl/gx/gxTransform.h
  sources.py
Labels: decomp, nw4r, p-medium

#26 Generate LCF using Jinja
  .github/workflows/build.yml
  .gitignore
  README.md
  build.py
  mkwutil/format_symbols.py
  mkwutil/gen_lcf.py
  mkwutil/symbols.py
  pack/dol.lcf.j2
  pack/rel.lcf.j2
  pack/symbols.txt
  requirements.txt
Labels: devops

#45 CI: Run pytest
  .github/workflows/test.yml
Labels: devops, enhancement, p-high

#40 Inline ASM: RVL/NAND
  asm/dol/text_8019b178_8019b314.s
  asm/dol/text_8019f1a8_801ae5d8.s
  mkwutil/sources.py
  pack/dol_objects.txt
  pack/dol_slices.csv
  source/rvl/nand/nand.c
Labels: decomp, p-low, rvl

#46 CI: Run mkwutil.graphic
  .github/workflows/pages.yml
  mkwutil/graphic.py
Labels: devops, docs, p-low

#64 Fix all warnings
  build.py
  mkwutil/sources.py
  source/dwc/common/dwc_error.c
  source/dwc/common/dwc_error.h
  source/dwc/common/dwc_init.c
  source/dwc/common/dwc_init.h
  source/dwc/common/dwc_memfunc.c
  source/dwc/common/dwc_memfunc.h
  source/dwc/common/dwci_error.h
  source/dwc/common/dwci_memfunc.h
  source/gamespy/GP/gpiSearch.c
  source/gamespy/common/gsDebug.h
  source/gamespy/common/gsPlatformSocket.h
  source/gamespy/common/gsXML.h
  source/gamespy/qr2/qr2.c
  source/platform/math.h
  source/rvl/so/so.h
  source/rvl/so/soCommon.c
Labels: bug, decomp, p-high

#68 Splitting: RVL/FS
  asm/dol/text_80124e80_80169bcc.s
  asm/dol/text_8016b49c_801981ec.s
  mkwutil/sources.py
  pack/dol_objects.txt
  pack/dol_slices.csv
  pack/symbols.txt
  source/decomp.h
  source/egg/core/eggHeap.cpp
  source/rvl/arc/binary_format.h
  source/rvl/fs/fs.c
  source/rvl/fs/fs.h
  source/rvl/ios/ios.h
  source/rvl/nand/nand.c
  source/rvl/os/osError.h
Labels: p-low, rvl, splitting

#75 Python Restructure
  .github/workflows/pages.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  build.py
  diff.py
  mkwutil/gen_asm.py
  mkwutil/gen_lcf.py
  mkwutil/lib/binary_blob.py
  mkwutil/lib/dol.py
  mkwutil/lib/ppc_dis.py
  mkwutil/lib/rel.py
  mkwutil/lib/rel_header.bin
  mkwutil/lib/slices.py
  mkwutil/lib/symbols.py
  mkwutil/pack_staticr_rel.py
  mkwutil/progress/graphic.py
  mkwutil/progress/graphic/index.html.j2
  mkwutil/progress/percent_decompiled.py
  mkwutil/project.py
  mkwutil/rel_repack.py
  mkwutil/sections.py
  mkwutil/tools/dump_dol_header.py
  mkwutil/tools/dump_elf_segments.py
  mkwutil/tools/dump_symbols.py
  mkwutil/tools/format_symbols.py
  mkwutil/verify_main_dol.py
  setup.py
  sources.py
  tests/test_slices.py
Labels: devops, enhancement

#77 CI: Remove dependency on 7-zip
  .github/workflows/build.yml
Labels: devops, enhancement

#78 CI: Setup venv and cache
  .github/workflows/build.yml
  .github/workflows/pages.yml
  .github/workflows/test.yml
Labels: devops, enhancement

#80 CI: Run gen_asm
  .github/workflows/build.yml
Labels: devops, enhancement

#85 CI: Add Linux build
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/pages.yml
  .gitignore
  build.py
  mkwutil/gen_asm.py
  mkwutil/gen_lcf.py
  pack/dol_objects.txt
  pack/rel.lcf.j2
  pack/rel_objects.txt
Labels: devops, help wanted

#87 Rewrite SliceTable.remove()
  mkwutil/lib/slices.py
Labels: devops

#88 percent_decompiled: Add split percentages
  .github/workflows/build.yml
  .github/workflows/pages.yml
  build.py
  mkwutil/lib/slices.py
  mkwutil/progress/graphic.py
  mkwutil/progress/graphic/index.html.j2
  mkwutil/progress/percent_decompiled.py
  mkwutil/project.py
  requirements.txt
  tests/test_slices.py
Labels: devops

#98 Decompile Util::Random
  pack/rel_objects.txt
  pack/rel_slices.csv
  source/game/util/Random.cpp
  source/game/util/Random.hpp
  sources.py
Labels: decomp, rel

#97 HACK.md: Document mkwutil
  HACK.md
Labels: docs

#102 CI: Upload badge artifact
  .github/workflows/build.yml
  mkwutil/progress/percent_decompiled.py
Labels: devops
